# Generated by Django 5.2.5 on 2025-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="Nazwisko")),
                ("active", models.BooleanField(default=True, verbose_name="aktywny")),
                ("order", models.PositiveIntegerField(verbose_name="kolejność")),
            ],
            options={
                "verbose_name": "staff",
                "verbose_name_plural": "staff",
                "ordering": ("order",),
            },
        ),
    ]
