# Generated by Django 5.2.5 on 2025-10-03 14:36

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                null=True,
                verbose_name="Nagłówki pod nawziskiem (pole listy)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="main_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="zdjęcie"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="typ",
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
