# Generated by Django 5.2.5 on 2025-10-03 14:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_person_description_person_main_photo_person_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="subheader",
            field=tinymce.models.HTMLField(
                default="brak", max_length=150, verbose_name="Funkcja"
            ),
            preserve_default=False,
        ),
    ]
