# Generated by Django 5.2.5 on 2025-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_person_subheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="subheader",
            field=models.CharField(max_length=150, verbose_name="Funkcja"),
        ),
    ]
