# Generated by Django 5.2.5 on 2025-10-03 15:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0005_alter_person_subheader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("o_mnie", tinymce.models.HTMLField(verbose_name="O mnie")),
                (
                    "procedury_intro",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="procedury nagłówek"
                    ),
                ),
                (
                    "procedury",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Procedury"
                    ),
                ),
                (
                    "rekomendacje_intro",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="rekomendacje nagłówek"
                    ),
                ),
                (
                    "kalendarium_intro",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="kalendarium nagłówek"
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.person",
                    ),
                ),
            ],
        ),
    ]
