# Generated by Django 5.2.5 on 2025-10-03 16:23

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1950),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Rok",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Styczeń"),
                            (2, "Luty"),
                            (3, "Marzec"),
                            (4, "Kwiecień"),
                            (5, "Maj"),
                            (6, "Czerwiec"),
                            (7, "Lipiec"),
                            (8, "Sierpień"),
                            (9, "Wrzesień"),
                            (10, "Październik"),
                            (11, "Listopad"),
                            (12, "Grudzień"),
                        ],
                        null=True,
                        verbose_name="Miesiąc",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("content", tinymce.models.HTMLField(verbose_name="Treść")),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalendarium",
                        to="staff.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kalendarium",
                "verbose_name_plural": "Kalendarium",
                "ordering": ["-year", "-month", "title"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                ("is_main", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="staff.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Galeria",
            },
        ),
        migrations.CreateModel(
            name="Rekomendacja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="rekomendacje/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("desc1", models.CharField(max_length=100)),
                ("desc2", models.CharField(max_length=100)),
                ("rekomendacja_content", tinymce.models.HTMLField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekomendacja",
                        to="staff.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rekomendacje",
            },
        ),
    ]
