# Generated by Django 5.2.5 on 2026-02-06 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0007_event_gallery_rekomendacja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2031),
                ],
                verbose_name="Rok",
            ),
        ),
    ]
