# Generated by Django 5.2.5 on 2026-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_alter_event_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
