# Generated by Django 5.2.5 on 2026-02-09 10:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_alter_event_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="description_en",
            field=tinymce.models.HTMLField(
                blank=True,
                null=True,
                verbose_name="Nagłówki pod nawziskiem (pole listy)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="description_pl",
            field=tinymce.models.HTMLField(
                blank=True,
                null=True,
                verbose_name="Nagłówki pod nawziskiem (pole listy)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="description_uk",
            field=tinymce.models.HTMLField(
                blank=True,
                null=True,
                verbose_name="Nagłówki pod nawziskiem (pole listy)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="subheader_en",
            field=models.CharField(max_length=150, null=True, verbose_name="Funkcja"),
        ),
        migrations.AddField(
            model_name="person",
            name="subheader_pl",
            field=models.CharField(max_length=150, null=True, verbose_name="Funkcja"),
        ),
        migrations.AddField(
            model_name="person",
            name="subheader_uk",
            field=models.CharField(max_length=150, null=True, verbose_name="Funkcja"),
        ),
    ]
