# Generated by Django 5.2.5 on 2026-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0010_alter_person_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
