# Generated by Django 5.2.5 on 2026-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0011_alter_person_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="slug",
        ),
    ]
