# Generated by Django 5.2.5 on 2025-09-01 14:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Procedura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=256)),
                (
                    "opis",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Opis badania"
                    ),
                ),
                (
                    "polega",
                    tinymce.models.HTMLField(
                        blank=True, default="", verbose_name="Na czym polega badanie"
                    ),
                ),
                (
                    "przebieg",
                    tinymce.models.HTMLField(
                        blank=True, default="", verbose_name="Przebieg badania"
                    ),
                ),
                (
                    "wskazania",
                    tinymce.models.HTMLField(
                        blank=True,
                        default="",
                        verbose_name="Wskazania do badania [POLE LISTY]",
                    ),
                ),
                (
                    "after",
                    tinymce.models.HTMLField(
                        blank=True, null=True, verbose_name="Po badaniu [POLE LISTY]"
                    ),
                ),
                (
                    "specjalizacja",
                    models.CharField(
                        choices=[
                            ("urologia", "urologia"),
                            ("kardiologia", "kardiologia"),
                            ("pulmunologia", "pulmunologia"),
                            ("rehabilitacja", "rehabilitacja"),
                            ("inne", "inne"),
                        ],
                        default="urologia",
                        max_length=20,
                    ),
                ),
                (
                    "typ_usługi",
                    models.CharField(
                        choices=[
                            ("B", "badanie"),
                            ("Z", "zabieg"),
                            ("P", "procedura"),
                            ("s", "sesja"),
                        ],
                        default="B",
                        max_length=25,
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="kolejność",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="aktywna")),
                ("lekarz", models.CharField(blank=True, max_length=200, null=True)),
                ("koszt", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cena_od", models.BooleanField(default=False)),
                ("czas_oczekiwania", models.IntegerField(blank=True, null=True)),
                ("czas_badania", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "pdf_pl",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="downloads/",
                        verbose_name="Instruktaż po polsku",
                    ),
                ),
                (
                    "pdf_en",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="downloads/",
                        verbose_name="Instruktaż po angielsku",
                    ),
                ),
                (
                    "pdf_uk",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="downloads/",
                        verbose_name="Instruktaż po ukraińsku",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "procedury",
                "ordering": ["order", "nazwa"],
            },
        ),
    ]
