# Generated by Django 5.2.5 on 2025-09-01 15:25

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedura",
            name="after_en",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Po badaniu [POLE LISTY]"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="after_pl",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Po badaniu [POLE LISTY]"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="after_uk",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Po badaniu [POLE LISTY]"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="nazwa_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="procedura",
            name="nazwa_pl",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="procedura",
            name="nazwa_uk",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="procedura",
            name="opis_en",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Opis badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="opis_pl",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Opis badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="opis_uk",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Opis badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="polega_en",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Na czym polega badanie"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="polega_pl",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Na czym polega badanie"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="polega_uk",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Na czym polega badanie"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="przebieg_en",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Przebieg badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="przebieg_pl",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Przebieg badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="przebieg_uk",
            field=tinymce.models.HTMLField(
                blank=True, default="", null=True, verbose_name="Przebieg badania"
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="wskazania_en",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                null=True,
                verbose_name="Wskazania do badania [POLE LISTY]",
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="wskazania_pl",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                null=True,
                verbose_name="Wskazania do badania [POLE LISTY]",
            ),
        ),
        migrations.AddField(
            model_name="procedura",
            name="wskazania_uk",
            field=tinymce.models.HTMLField(
                blank=True,
                default="",
                null=True,
                verbose_name="Wskazania do badania [POLE LISTY]",
            ),
        ),
    ]
